import llm_interface
import sql_verifier
import sqlite3

#Interface for executing SQL queries generated by the LLM
def execute_command(user_input):
    #First sends user input through llm for a response query
    query = user_input #DEBUG
    #query = llm_interface.generate_query(user_input)
    #Then validates the query 
    if sql_verifier.validate_query(query):
        #Run the query and return results
        results = run_query(query)
        return results
    return "not a valid query"

def run_query(query):
    conn = sqlite3.connect('database.db')
    cursor = conn.cursor()
    try:
        cursor.execute(query)
        results = cursor.fetchall()
        conn.commit()
        return results
    except Exception as e:
        return f"An error occurred: {e}"
    finally:
        conn.close()