import llm_interface
import sql_verifier
import schema_manager
import os
from dotenv import load_dotenv
import re

load_dotenv("CONFIG_FILE")
MAX_ATTEMPTS = int(os.getenv("MAX_ATTEMPTS", "3"))
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

#Interface for executing SQL queries generated by the LLM
def execute_command(user_input):

    #Previous Attempts at querying.
    previous_attempts = []

    for _ in range(MAX_ATTEMPTS):
    
        #First sends user input through llm for a response query
        query = llm_interface.generate_query(user_input, previous_attempts)

        #Then validates the query 
        if query == "DENIED":
            return "Are you sure what you're doing is correct.."

        if not sql_verifier.validate_query(query):
            attempt = [query, "Invalid query given."]
            previous_attempts.append(attempt)
            continue
        
        if DEBUG:
            print(f"Generated Query: {query}")

        #Run the query and return results
        results, error = schema_manager.run_user_query(query)

        if DEBUG:
            print(f"Query Results: {results}, Error: {error}")

        attempt, restart = check_result(query, results, error)
        if restart:
            previous_attempts.append(attempt)
            continue
        
        pretty_results = llm_interface.results_to_text(user_input, query, results)
        return pretty_results
    
    return "Exceeded the number of attempt. Please rephrase the query."

def check_result(query, results, error):
    if error:
            attempt = [query, f"Error on execution: {error}"]
            return attempt
        
    no_results = (
        len(results) == 0 or
        results == [(None,)]
    )
        
    count_empty = (
        results == [(0,)] and
        bool(re.search(r"WHERE.*'[^']*'", query, re.IGNORECASE))
    )

    if (no_results or count_empty) and "WHERE" in query.upper():
        attempt = [query, "Returned zero rows. Likely a missed filtering."]
        return attempt, True
    
    return "", False


