import schema_manager
import sqlite3

# This file is responsible for verifying the SQL queries generated by the LLM.
# Requirements:
# SQL queries must: only use SELECT, use valid tables, and valid columns,
# Lastly, SQL cannot be  directly called.
# Further checks will be done later.

def validate_query(query):
    #get table schemas
    table_schemas = schema_manager.get_tables()

    #check if query only uses SELECT
    if not query.strip().upper().startswith("SELECT"):
        print("DEBUG Query validation failed: Query must start with SELECT.")
        return False
    
    #This helps stop multiple statements, and direct calls.

    if ";" in query.strip().rstrip(";"):
        print("DEBUG Query validation failed: Query cannot contain semicolons.")
        return False

    #Additional check to stop not good calls
    if "DROP" in query.upper() or "DELETE" in query.upper() or "INSERT" in query.upper() or "UPDATE" in query.upper():
        print("DEBUG Query validation failed: Query cannot contain DROP, DELETE, INSERT, or UPDATE.")
        return False
    
    
